### PR TITLE
Zip Generator Action PR

### PR DESCRIPTION
**Pull request by minh-pham1**
This PR was created automatically by Github ZIP Generator Action.

### CODE REVIEW

**Comment by wwfiserv** [comment]
@minh-pham1 do you have a separate request/branch for develop/stage/main? I don't want to have this merge cause issues with our production content as preview contains content I don't want merged there if we use the same branch.

**Comment by minh-pham1** [comment]
This is automatically created to create the zip using the API specs from the branch being pushed to (i.e. you made a change to api on `preview`, so it auto-created new zip just for the `preview` branch). It won't create the new zip for the other branches unless you also make changes to those.

If this is regarding how `preview` branch is shared on all env, it's always been the case (docs, apis, and zip download are the same for `preview` across all env) so this new change shouldn't change anything. Essentially, instead of pushing zip files to the `tenants-data` repo it's just pushing to your local repo now.

Does that answer your question?

**Comment by wwfiserv** [comment]
@minh-pham1 ok, thought this was an automatic process with the checks, never seen a separate PR

**Review by wwfiserv — COMMENTED** [review]
ok

**Comment by minh-pham1** [comment]
Unfortunately the Github Action cannot force-push into the repository (due to the pull request rule) so it has to create a PR. It should auto-merge in the future though.

**Pull request merged**
